### ISSUE TITLE
settingsUtility:WindowUtility.SavePosition="True" Error Messages

### ISSUE THREAD

**Issue by comeero** [Zumwani/Common-wpf#1]
Hi there,

I'm trying your Settings.Wpf utility right now but I have some problems to get it running.

I added those 2 lines to my XAML:
`xmlns:settingsUtility="common://settings"`
`settingsUtility:WindowUtility.SavePosition="True"`

But I get those error messages:
The name "WindowUtility" does not exist in the namespace "common://settings"
The attachable property 'SavePosition' was not found in type 'WindowUtility'.

The following line does not give any errors:
`Common.SavePosition="True"`

but it crashes when the program is starting with an error that Common-Wpf has to be installed.

Any help is appreciated. I use the nuget package if it matters. Thank you.

**Comment by Zumwani** [comment]
Hi, sorry about that, I've forgotten to update the examples.

As you noticed, I've put most attached properties into the Common class. Then I proceeded to have issues with getting multiple classes with the same name in multiple assemblies working or something like that, and the easiest solution to that was to just put SavePosition into Common.Utility, so yeah you'll need Common.Utility to use that. Odd that it is still listed though even when you don't have it installed :D

Also, just to clarify, SavePosition does not need Common.Settings to be installed.

**Comment by comeero** [comment]
Hi Andreas,

thanks for your prompt reply. :-)

It is listed because I installed Common-wpf.Utility. 

The really odd thing is that the program crashes right after the start with an Exception that Common.Utility is not installed. Of course Common.Utility dll is in the same folder as the app.

![image](https://user-images.githubusercontent.com/60378441/190101640-a167bf8b-b17b-4830-9ccf-0fb154680bbe.png)
![image](https://user-images.githubusercontent.com/60378441/190101824-0e1442e6-3d61-4e0d-a9fd-806edb25bd7e.png)

I guess there is an reference missing though

**Comment by Zumwani** [comment]
Hi, looking at the code (its been a while since I wrote it), it seems I was wrong in it not needing common-wpf.Settings, I'm currently using reflection to use SettingsUtility, which, yeah, not fantastic. It is odd that its never failed for me though, but I'll see if I can't find a better solution, sorry for wasting your time :D

**Comment by Zumwani** [comment]
Alright, I moved SavePosition back into Common.Settings, and figured out why I didn't get it to work last time, it was due to the namespaces being different, which seems to be supported for two namespaces in the same assembly, but not multiple assemblies. 

So it works now when I use the same namespace in both assemblies. I've pushed an update on nuget, so it should be available for download soon.

**Comment by comeero** [comment]
Fantastic support! Thank you. I'll try it

**Comment by comeero** [comment]
Works perfectly now! Thanks again for your support :-)

**Comment by Zumwani** [comment]
No problem :D

**Comment by Zumwani** [comment]
Hi, just wanted to mention the fact that I ended up running into more issues relating to using the same name Common in multiple assemblies, and it seems that they overwrite each other. It only worked in my test and your project because of the order of the assemblies being loaded, so I've updated the package once more and Common.SavePosition is now Settings.SavePosition.

**Comment by comeero** [comment]
Oh okay, did you publish an update on NuGet?

**Comment by Zumwani** [comment]
Sorry, I forgot to delete my test project that I made, which failed the github workflow. I've fixed it now, the package should be available soon :D
